[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@eth-optimism/=node_modules/@eth-optimism/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@thirdweb-dev/=node_modules/@thirdweb-dev/",
    "ds-test/=node_modules/@thirdweb-dev/dynamic-contracts/lib/forge-std/lib/ds-test/",
    "erc721a-upgradeable/=node_modules/erc721a-upgradeable/",
    "forge-std/=node_modules/@thirdweb-dev/dynamic-contracts/lib/forge-std/",
    "sstore2/=node_modules/@thirdweb-dev/dynamic-contracts/lib/sstore2/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
